### ISSUE TITLE
can't mount rpc_pipefs

### ISSUE THREAD

**Issue by s13n** [ehough/docker-nfs-server#11] opened 2018-08-23 16:50 UTC
I tried unsuccessfully to run the nfs-server image on an up-to-date Ubuntu LTS 18.04 host. The setup is pretty similar to the example given in the Usage section of the docs.

There appears to be a problem with the mounting of a file system.

The docker run command is:
`$ docker run -v /srv/nfs:/nfs -v /srv/exports.nfs:/etc/exports:ro --cap-add SYS_ADMIN -p 2049:2049 erichough/nfs-server`

Its output:
`...`
`mount: rpc_pipefs is write-protected, mounting read-only`
`mount: cannot mount rpc_pipefs read-only`
`...`

**Comment by ehough** [comment] 2018-08-24 06:49
At first glance this looks like a duplicate of #5, which occurs when AppArmor is enabled on the Docker host. Is that the case with you? If so, check out [these instructions](https://github.com/ehough/docker-nfs-server/blob/develop/doc/feature/apparmor.md) for the solution.

Let us know!

**Comment by ehough** [comment] 2018-09-04 18:37
@s13n were you able to resolve this issue? Just checking in.

**Closed** 2018-09-12 20:30 UTC
